pipeline
{
    agent any

    stages
    {
        stage('Checkout From Github')
        {
            steps
            {
                echo 'Checking out code from GitHub repository'
                git branch: 'new_test', url: 'https://github.com/Infantselva015/CICD_Practise.git'
                echo 'Code checkout completed'
            }
        }

        stage('Installing Python Dependencies')
        {
            steps
            {
                sh """
                python3 -m venv venv
                . venv/bin/activate
                pip install -r req.txt
                """
            }
        }

        stage('Run Test')
        {
            steps
            {
                sh """
                . venv/bin/activate
                pytest
                """
            }
        }

        stage('Build Complete')
        {
            steps
            {
                echo 'Build and tests completed successfully!'
            }
        }

    }
}